Creating a "Matrix Operations Tool" using Python and the NumPy library. This application will allow users to input matrices and perform operations like addition, subtraction, multiplication, transpose, and determinant calculation. It Includes an interactive interface to display results in a structured format.

In [1]:
# Import necessary libraries
import numpy as np
import os


In [2]:
# Function to take matrix input from user
def mat_input():

    # Get matrix dimensions from user
    # Example: 2,3 for a 2x3 matrix
    try:
        dimensions_str = input("Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2): ")
        shape = tuple(map(int, dimensions_str.split(',')))
    except ValueError:
        print("Invalid input for dimensions. Please enter integers only.")
        return

    # Calculate total number of elements needed
    total_elements = np.prod(shape)

    # Get matrix elements from user
    try:
        elements_str = input(f"Enter {total_elements} elements separated by spaces: ")
        elements_list = list(map(int, elements_str.split()))
    except ValueError:
        print("Invalid input for elements. Please enter numbers only.")
        return

    # Validate if correct number of elements is entered
    if len(elements_list) != total_elements:
        print(f"Error: Expected {total_elements} elements, but got {len(elements_list)}.")
        return

    # Convert list into NumPy array and reshape it
    numpy_array = np.array(elements_list)
    multi_dim_array = numpy_array.reshape(shape)

    # Display the created matrix
    print("Created NumPy Array:")
    print(multi_dim_array)

    # Return the matrix
    return multi_dim_array


In [3]:
# Function to perform matrix addition
def addition(m1, m2):
    return np.add(m1, m2)


# Function to perform matrix subtraction
def subtraction(m1, m2):
    return np.subtract(m1, m2)


# Function to perform matrix multiplication
def multiplication(m1, m2):
    return np.matmul(m1, m2)


# Function to find transpose of a matrix
def transpose(m):
    return np.transpose(m, axes=(1, 0))


# Function to calculate determinant of a matrix
def determinant(m):
    return np.linalg.det(m)


In [4]:
# Main function to run the program
def main():

    # Infinite loop for menu-driven program
    while True:

        # Clear screen (Windows only)
        os.system("cls")

        # Display main menu
        print("Welcome to matrix calculator")
        print("----------------------------")
        print("Press 1 for Addition")
        print("Press 2 for Subtraction")
        print("Press 3 for Multiplication")
        print("Press 4 for Transpose")
        print("Press 5 for Determinant")
        print("Press 6 to Exit")
        print("----------------------------")

        # Take user choice
        ch = int(input("Enter your choice : "))


        # ----------- Addition -----------
        if ch == 1:

            print("Welcome to Matrix Addition")

            # Take input of both matrices
            m1 = mat_input()
            m2 = mat_input()

            # Check if shapes are same
            if m1.shape == m2.shape:

                # Perform addition
                add = addition(m1, m2)

                # Display result
                print("----------------------------")
                print("The Sum of matrix is\n", add)
                print("----------------------------")

            else:
                print("Matrices must have same shape!")

            input("Press Enter to continue...")


        # ----------- Subtraction -----------
        elif ch == 2:

            print("Welcome to Matrix Subtraction")

            m1 = mat_input()
            m2 = mat_input()

            # Check if shapes are same
            if m1.shape == m2.shape:

                sub = subtraction(m1, m2)

                print("----------------------------")
                print("The Difference of matrix is\n", sub)
                print("----------------------------")

            else:
                print("Matrices must have same shape!")

            input("Press Enter to continue...")


        # ----------- Multiplication -----------
        elif ch == 3:

            print("Welcome to Matrix Multiplication")

            m1 = mat_input()
            m2 = mat_input()

            # Check multiplication compatibility
            if m1.shape[1] == m2.shape[0]:

                mul = multiplication(m1, m2)

                print("----------------------------")
                print("The Product of matrix is\n", mul)
                print("----------------------------")

            else:
                print("Number of columns of first matrix must be equal to rows of second matrix!")

            input("Press Enter to continue...")


        # ----------- Transpose -----------
        elif ch == 4:

            print("Welcome to Matrix Transpose")

            m = mat_input()

            tra = transpose(m)

            print("----------------------------")
            print("The Transpose of matrix is\n", tra)
            print("----------------------------")

            input("Press Enter to continue...")


        # ----------- Determinant -----------
        elif ch == 5:

            print("Welcome to Matrix Determinant Calculator")

            m = mat_input()

            # Check if matrix is square
            if m.shape[0] == m.shape[1]:

                det = determinant(m)

                print("----------------------------")
                print("The Determinant of matrix is\n", int(round(det)))
                print("----------------------------")

            else:
                print("Given matrix is not square")

            input("Press Enter to continue...")


        # ----------- Exit -----------
        elif ch == 6:

            os.system("cls")
            print("Thank you for using Matrix Calculator.")
            break


        # ----------- Invalid Input -----------
        else:

            print("Wrong input!")
            input("Press any key to start again...")



In [6]:
# Run the main function
main()


Welcome to matrix calculator
----------------------------
Press 1 for Addition
Press 2 for Subtraction
Press 3 for Multiplication
Press 4 for Transpose
Press 5 for Determinant
Press 6 to Exit
----------------------------


Enter your choice :  1


Welcome to Matrix Addition


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  2,3
Enter 6 elements separated by spaces:  1 5 9 7 5 3


Created NumPy Array:
[[1 5 9]
 [7 5 3]]


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  2,3
Enter 6 elements separated by spaces:  7 5 3 1 9 4


Created NumPy Array:
[[7 5 3]
 [1 9 4]]
----------------------------
The Sum of matrix is
 [[ 8 10 12]
 [ 8 14  7]]
----------------------------


Press Enter to continue... 


Welcome to matrix calculator
----------------------------
Press 1 for Addition
Press 2 for Subtraction
Press 3 for Multiplication
Press 4 for Transpose
Press 5 for Determinant
Press 6 to Exit
----------------------------


Enter your choice :  2


Welcome to Matrix Subtraction


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  2,3
Enter 6 elements separated by spaces:  1 6 7 4 9 8


Created NumPy Array:
[[1 6 7]
 [4 9 8]]


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  2,3
Enter 6 elements separated by spaces:  3 2 6 5 7 4


Created NumPy Array:
[[3 2 6]
 [5 7 4]]
----------------------------
The Difference of matrix is
 [[-2  4  1]
 [-1  2  4]]
----------------------------


Press Enter to continue... 


Welcome to matrix calculator
----------------------------
Press 1 for Addition
Press 2 for Subtraction
Press 3 for Multiplication
Press 4 for Transpose
Press 5 for Determinant
Press 6 to Exit
----------------------------


Enter your choice :  3


Welcome to Matrix Multiplication


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  2,3
Enter 6 elements separated by spaces:  1 2 5 7 9 4


Created NumPy Array:
[[1 2 5]
 [7 9 4]]


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  3,3
Enter 9 elements separated by spaces:  1 74 7 85 9 6 4 2 3


Created NumPy Array:
[[ 1 74  7]
 [85  9  6]
 [ 4  2  3]]
----------------------------
The Product of matrix is
 [[191 102  34]
 [788 607 115]]
----------------------------


Press Enter to continue... 


Welcome to matrix calculator
----------------------------
Press 1 for Addition
Press 2 for Subtraction
Press 3 for Multiplication
Press 4 for Transpose
Press 5 for Determinant
Press 6 to Exit
----------------------------


Enter your choice :  4


Welcome to Matrix Transpose


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  3,3
Enter 9 elements separated by spaces:  1 7 5 2 9 4 5 6 3


Created NumPy Array:
[[1 7 5]
 [2 9 4]
 [5 6 3]]
----------------------------
The Transpose of matrix is
 [[1 2 5]
 [7 9 6]
 [5 4 3]]
----------------------------


Press Enter to continue... 


Welcome to matrix calculator
----------------------------
Press 1 for Addition
Press 2 for Subtraction
Press 3 for Multiplication
Press 4 for Transpose
Press 5 for Determinant
Press 6 to Exit
----------------------------


Enter your choice :  5


Welcome to Matrix Determinant Calculator


Enter the dimensions (shape) as comma-separated integers (e.g., 2,3 or 2,2,2):  3,3
Enter 9 elements separated by spaces:  4 5 8 9 3 1 4 5 5


Created NumPy Array:
[[4 5 8]
 [9 3 1]
 [4 5 5]]
----------------------------
The Determinant of matrix is
 99
----------------------------


Press Enter to continue... 


Welcome to matrix calculator
----------------------------
Press 1 for Addition
Press 2 for Subtraction
Press 3 for Multiplication
Press 4 for Transpose
Press 5 for Determinant
Press 6 to Exit
----------------------------


Enter your choice :  6


Thank you for using Matrix Calculator.
